Added support for Ubuntu
ExperitestOfficial/ansible-role-web-studio pull request #19
Opened 2023-11-03 07:04 UTC by prahastakumar

Added support for Ubuntu

2023-11-20 16:07 UTC, eyalneumann commented
LGTM, you mostly just split it for 2 perquisite files, i assume it works,  but someone else from ops should approve as well.

2023-12-11 08:03 UTC, OmprakashPaliwal requested changes

2023-12-11 08:03 UTC, OmprakashPaliwal commented on tasks/main.yml
> +  when: (ansible_os_family | lower) not in ['redhat', 'debian']
We have removed support for windows?

2023-12-11 11:25 UTC, OmprakashPaliwal approved these changes

2023-12-11 11:25 UTC, merged